// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEt-ltX2X1vI3D4hhhcuIbFYMph3oJJfc',
    appId: '1:659368015427:web:7d36ef1f870611459086f6',
    messagingSenderId: '659368015427',
    projectId: 'shared-lives',
    authDomain: 'shared-lives.firebaseapp.com',
    databaseURL: 'https://shared-lives-default-rtdb.firebaseio.com',
    storageBucket: 'shared-lives.firebasestorage.app',
    measurementId: 'G-GMTNBFZF7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2-dbLEr7cZfF4tQMl7pGfxmefDRBuP_k',
    appId: '1:659368015427:android:9e5730d2316623079086f6',
    messagingSenderId: '659368015427',
    projectId: 'shared-lives',
    databaseURL: 'https://shared-lives-default-rtdb.firebaseio.com',
    storageBucket: 'shared-lives.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEt-ltX2X1vI3D4hhhcuIbFYMph3oJJfc',
    appId: '1:659368015427:web:229f6bd233a9ef219086f6',
    messagingSenderId: '659368015427',
    projectId: 'shared-lives',
    authDomain: 'shared-lives.firebaseapp.com',
    databaseURL: 'https://shared-lives-default-rtdb.firebaseio.com',
    storageBucket: 'shared-lives.firebasestorage.app',
    measurementId: 'G-MSJZGCVFXM',
  );

}